
/* 
 * https://closure-compiler.appspot.com/home
 * @compilation_level ADVANCED_OPTIMIZATIONS
 */
function e(a,c){this.x=a;this.y=c}var k=new e(0,0),m=new e(0,1),p=new e(0,-1),r=new e(1,0),t=new e(-1,0);Object.freeze(e);Object.freeze(k);Object.freeze(m);Object.freeze(p);Object.freeze(r);Object.freeze(t);
var u={query:"#canvas-output",g:new e(1800,900),u:100,B:1},v={count:2E3,m:u.g,h:new e(u.g.x/2,u.g.y/2),angle:new e(0,2*Math.PI),speed:300,D:2,j:"#ffffff #ffffe6 #ffffcc #ffffb3 #ffff99 #ffff80 #ffff66 #ffff4d #ffff33 #ffff1a #ffff00 #e6e600 #cccc00 #b3b300 #999900 #808000 #666600 #4d4d00 #333300 #1a1a00 #000000".split(" "),v:0,C:0};
function w(a){var c=document.querySelector(u.query);c.width=u.g.x;c.height=u.g.y;c.style.width=u.g.x;c.style.height=u.g.y;this.canvas=c;this.l=this.canvas.getContext("2d");this.A=a;this.g=u.g;this.i=[];for(a=0;a<v.count;a++)this.i.push(new x);this.s()}w.prototype.clear=function(){this.l.fillStyle="black";this.l.fillRect(0,0,this.g.x,this.g.y)};w.prototype.s=function(){this.A(this);requestAnimationFrame(this.s.bind(this))};
function x(){this.m=v.m;if(Array.isArray(v.h)){var a=v.h[0];var c=v.h[1];a=new e(Math.random()*(c.x-a.x)+a.x,Math.random()*(c.y-a.y)+a.y)}else a=v.h;this.h=a;this.angle=v.angle instanceof e?Math.random()*(v.angle.y-v.angle.x)+v.angle.x:v.angle;this.j=v.j;this.color="number"===typeof v.v?this.j[v.v]:this.j[Math.floor(Math.random()*v.j.length)];this.o=!1}
x.prototype.move=function(){var a=this.h;var c=new e(Math.cos(this.angle)*v.speed*.016,Math.sin(this.angle)*v.speed*.016);a=new e(a.x+c.x,a.y+c.y);!this.o&&(0>a.x||a.x>this.m.x||0>a.y||a.y>this.m.y)?(a=this.h,c=this.m,this.h=new e(Math.max(k.x,Math.min(a.x,c.x)),Math.max(k.y,Math.min(a.y,c.y))),this.angle=-this.angle+.4*Math.random()-.2,a=this.j.indexOf(this.color),a=a+1===this.j.length?0:a+1,this.color=this.j[a],this.o=!0):(this.h=a,this.o=!1)};var y=[];
new w(function(a){a.F=[];var c=a.g.x/u.u,z=1/(a.g.x/c),A=1/(a.g.y/(a.g.y/u.u));a.l.fillStyle="rgba(0, 0, 0, "+v.C+")";a.l.fillRect(0,0,a.g.x,a.g.y);for(var n=0;n<a.i.length;n++){var q=a.i[n].h,b=Math.floor(Math.floor(q.y*A)*c+Math.floor(q.x*z));"undefined"==typeof y[b]&&(y[b]=0);y[b]+=1;var h=void 0,f=void 0,l=void 0,g=a.i[n].angle-Math.PI/2,d=u.B;b=[d+b+c*d+d,d+b+c*d,d+b+c*d-d,d+b-d,d+b-c*d-d,d+b-c*d,d+b-c*d+d,d+b+d];5.105<g&&5.89>=g?(l=0,f=[b[7],b[0],b[1]]):5.89<g||.392>=g?(l=1,f=[b[0],b[1],b[2]]):
.392<g&&1.178>=g?(l=2,f=[b[1],b[2],b[3]]):1.178<g&&1.963>=g?(l=3,f=[b[2],b[3],b[4]]):1.963<g&&2.748>=g?(l=4,f=[b[3],b[4],b[5]]):2.748<g&&3.534>=g?(l=5,f=[b[4],b[5],b[6]]):3.534<g&&4.319>=g?(l=6,f=[b[5],b[6],b[7]]):4.319<g&&5.105>=g&&(l=7,f=[b[6],b[7],b[0]]);for(b=g=0;3>b;b++)d=y[f[b]],"number"==typeof d&&d>g&&(g=d,h=l+b-1);h=-1===h?7:h;h=8===h?0:h;f=7===l+h?7===h?1:-1:h<l?1:-1;"number"==typeof h&&l!=h&&(a.i[n].angle+=v.D*f*.016*Math.random());a.i[n].move();h=a.i[n].h;l=a.i[n].color;f=a.l;f.lineCap=
"round";f.lineJoin="round";f.strokeStyle=l;f.beginPath();f.moveTo(q.x,q.y);f.lineTo(h.x,h.y);f.stroke()}});