
/* 
 * https://closure-compiler.appspot.com/home
 * @compilation_level ADVANCED_OPTIMIZATIONS
 */
function d(a,b){return[a,b]}d.s=function(a){return Math.sqrt(Math.pow(a[0],2)+Math.pow(a[1],2))};d.normalize=function(a){var b=d.s(a);return 0!=b?d.D(a,b):[0,0]};d.floor=function(a){return[Math.floor(a[0]),Math.floor(a[1])]};d.ceil=function(a){return[Math.ceil(a[0]),Math.ceil(a[1])]};d.round=function(a){return[Math.round(a[0]),Math.round(a[1])]};d.add=function(a,b){return[a[0]+b[0],a[1]+b[1]]};d.multiply=function(a,b){return[a[0]*b[0],a[1]*b[1]]};d.D=function(a,b){return[a[0]/b,a[1]/b]};
d.F=function(a,b){return a[0]*b[0]+a[1]*b[1]};d.C=function(a,b,p){return[Math.max(b[0],Math.min(a[0],p[0])),Math.max(b[1],Math.min(a[1],p[0]))]};d.random=function(a,b){return[Math.random()*(b-a)+a,Math.random()*(b-a)+a]};d.I=function(){var a=f.h[0],b=f.h[1];return[Math.random()*(b[0]-a[0])+a[0],Math.random()*(b[0]-a[1])+a[1]]};d.angle=function(a,b){var p=Math.acos(d.F(a,b)/(d.s(a)*d.s(b)));return isNaN(p)?0:p};d.M=[0,0];d.L=[0,1];d.G=[0,-1];d.right=[1,0];d.left=[-1,0];Object.freeze(d);Object.freeze(d.M);
Object.freeze(d.L);Object.freeze(d.G);Object.freeze(d.right);Object.freeze(d.left);var m={query:"#canvas-output",g:[1800,900],v:100,H:1},f={count:4E3,l:[[0, 0],m.g],h:[m.g[0]/2,m.g[1]/2],angle:[0, Math.PI * 2],speed:300,K:2,j:"#b3b3ff #9999ff #8080ff #6666ff #4d4dff #3333ff #1a1aff #0000ff #0000e6 #0000cc #0000b3 #000099 #000080 #000066 #00004d".split(" "),A:0,J:0.01};
function q(a){var b=document.querySelector(m.query);b.width=m.g[0];b.height=m.g[1];b.style.width=m.g[0];b.style.height=m.g[1];this.canvas=b;this.m=this.canvas.getContext("2d");this.B=a;this.g=m.g;this.i=[];for(a=0;a<f.count;a++)this.i.push(new t);this.u()}q.prototype.clear=function(){this.m.fillStyle="black";this.m.fillRect(0,0,this.g[0],this.g[1])};q.prototype.u=function(){this.B(this);requestAnimationFrame(this.u.bind(this))};
function t(){this.l=f.l;this.h=Array.isArray(f.h[0])&&Array.isArray(f.h[1])?d.I():f.h;this.angle=Array.isArray(f.angle)?Math.random()*(f.angle[1]-f.angle[0])+f.angle[0]:f.angle;this.j=f.j;this.color="number"===typeof f.A?this.j[f.A]:this.j[Math.floor(Math.random()*f.j.length)];this.o=!1}
t.prototype.move=function(){var a=d.add(this.h,[Math.cos(this.angle)*f.speed*.016,Math.sin(this.angle)*f.speed*.016]);!this.o&&(a[0]<this.l[0][0]||a[0]>this.l[1][0]||a[1]<this.l[0][1]||a[1]>this.l[1][1])?(this.h=d.C(this.h,this.l[0],this.l[1]),this.angle=-this.angle+.4*Math.random()-.2,a=this.j.indexOf(this.color),a=a+1===this.j.length?0:a+1,this.color=this.j[a],this.o=!0):(this.h=a,this.o=!1)};var u=[];
new q(function(a){a.N=[];var b=a.g[0]/m.v,p=1/(a.g[0]/b),v=1/(a.g[1]/(a.g[1]/m.v));a.m.fillStyle="rgba(0, 0, 0, "+f.J+")";a.m.fillRect(0,0,a.g[0],a.g[1]);for(var n=0;n<a.i.length;n++){var r=a.i[n].h,c=Math.floor(Math.floor(r[1]*v)*b+Math.floor(r[0]*p));"undefined"==typeof u[c]&&(u[c]=0);u[c]+=1;var k=void 0,g=void 0,l=void 0,h=a.i[n].angle+Math.PI*0.5,e=m.H;c=[e+c+b*e+e,e+c+b*e,e+c+b*e-e,e+c-e,e+c-b*e-e,e+c-b*e,e+c-b*e+e,e+c+e];5.105<h&&5.89>=h?(l=0,g=[c[7],c[0],c[1]]):5.89<h||.392>=h?(l=1,g=[c[0],
c[1],c[2]]):.392<h&&1.178>=h?(l=2,g=[c[1],c[2],c[3]]):1.178<h&&1.963>=h?(l=3,g=[c[2],c[3],c[4]]):1.963<h&&2.748>=h?(l=4,g=[c[3],c[4],c[5]]):2.748<h&&3.534>=h?(l=5,g=[c[4],c[5],c[6]]):3.534<h&&4.319>=h?(l=6,g=[c[5],c[6],c[7]]):4.319<h&&5.105>=h&&(l=7,g=[c[6],c[7],c[0]]);for(c=h=0;3>c;c++)e=u[g[c]],"number"==typeof e&&e>h&&(h=e,k=l+c-1);k=-1===k?7:k;k=8===k?0:k;g=7===l+k?7===k?1:-1:k<l?1:-1;"number"==typeof k&&l!=k&&(a.i[n].angle+=f.K*g*.016*Math.random());a.i[n].move();k=a.i[n].h;l=a.i[n].color;g=
a.m;g.lineCap="round";g.lineJoin="round";g.strokeStyle=l;g.beginPath();g.moveTo(r[0],r[1]);g.lineTo(k[0],k[1]);g.stroke()}});